# Generated by Django 4.2.7 on 2025-11-21 14:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeviceStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Mã thiết bị"
                    ),
                ),
                (
                    "device_name",
                    models.CharField(max_length=100, verbose_name="Tên thiết bị"),
                ),
                (
                    "is_online",
                    models.BooleanField(
                        default=False, verbose_name="Trạng thái kết nối"
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Lần kết nối cuối"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Địa chỉ IP"
                    ),
                ),
                (
                    "firmware_version",
                    models.CharField(
                        default="1.0.0",
                        max_length=20,
                        verbose_name="Phiên bản firmware",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trạng thái thiết bị",
                "verbose_name_plural": "Trạng thái thiết bị",
            },
        ),
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        help_text="Nhiệt độ đo được từ cảm biến DHT11",
                        verbose_name="Nhiệt độ (°C)",
                    ),
                ),
                (
                    "humidity",
                    models.FloatField(
                        help_text="Độ ẩm đo được từ cảm biến DHT11",
                        verbose_name="Độ ẩm (%)",
                    ),
                ),
                (
                    "gas_level",
                    models.FloatField(
                        help_text="Nồng độ khí độc hại từ cảm biến MQ-135",
                        verbose_name="Mức Gas (ppm)",
                    ),
                ),
                (
                    "dust_density",
                    models.FloatField(
                        help_text="Nồng độ bụi mịn từ cảm biến GP2Y10",
                        verbose_name="Mật độ bụi (µg/m³)",
                    ),
                ),
                (
                    "aqi",
                    models.IntegerField(
                        help_text="Air Quality Index được tính từ các cảm biến",
                        verbose_name="Chỉ số AQI",
                    ),
                ),
                (
                    "air_quality_status",
                    models.CharField(
                        choices=[
                            ("GOOD", "Tốt"),
                            ("MODERATE", "Trung bình"),
                            ("UNHEALTHY_SENSITIVE", "Không tốt cho nhóm nhạy cảm"),
                            ("UNHEALTHY", "Không tốt"),
                            ("VERY_UNHEALTHY", "Rất không tốt"),
                            ("HAZARDOUS", "Nguy hại"),
                        ],
                        max_length=30,
                        verbose_name="Mức độ chất lượng không khí",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        default="ESP32_001", max_length=50, verbose_name="Mã thiết bị"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Thời gian ghi nhận",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dữ liệu cảm biến",
                "verbose_name_plural": "Dữ liệu cảm biến",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="monitor_sen_timesta_fcdbf7_idx"
                    ),
                    models.Index(
                        fields=["device_id", "-timestamp"],
                        name="monitor_sen_device__d43576_idx",
                    ),
                ],
            },
        ),
    ]
