# Generated by Django 4.2.7 on 2025-11-26 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "__first__"),
        ("monitor", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="sensordata",
            name="monitor_sen_device__d43576_idx",
        ),
        migrations.RemoveField(
            model_name="sensordata",
            name="device_id",
        ),
        migrations.AddField(
            model_name="sensordata",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sensor_data",
                to="devices.device",
                verbose_name="Thiết bị",
            ),
        ),
        migrations.AddIndex(
            model_name="sensordata",
            index=models.Index(
                fields=["device", "-timestamp"], name="monitor_sen_device__d43576_idx"
            ),
        ),
    ]
