# Generated by Django 4.2.7 on 2025-11-26 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Mã thiết bị"
                    ),
                ),
                (
                    "device_name",
                    models.CharField(max_length=255, verbose_name="Tên thiết bị"),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=255, verbose_name="Vị trí"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Mô tả")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Hoạt động"),
                            ("inactive", "Không hoạt động"),
                            ("maintenance", "Bảo trì"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "is_online",
                    models.BooleanField(default=False, verbose_name="Đang kết nối"),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Lần kết nối cuối"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Địa chỉ IP"
                    ),
                ),
                (
                    "firmware_version",
                    models.CharField(
                        default="1.0.0",
                        max_length=20,
                        verbose_name="Phiên bản firmware",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
            ],
            options={
                "verbose_name": "Thiết bị",
                "verbose_name_plural": "Thiết bị",
                "db_table": "devices",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeviceKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="API Key"
                    ),
                ),
                (
                    "secret_key",
                    models.CharField(max_length=128, verbose_name="Secret Key"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "device",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="key",
                        to="devices.device",
                        verbose_name="Thiết bị",
                    ),
                ),
            ],
            options={
                "verbose_name": "Khóa thiết bị",
                "verbose_name_plural": "Khóa thiết bị",
                "db_table": "device_keys",
            },
        ),
    ]
